### ISSUE TITLE
fix whatever's going wrong with subprocess.call

### ISSUE THREAD

**Issue by Kedersha** [roedoejet/waldayu_resource_creator#12]
We don't know what the situation here is, but @mariannehuijsmans and I have tried a few different things to no avail.

The error we're getting is:
`$ python main.py heiltsuk --init
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    subprocess.call('python creators/{cversion}/waldayu.py {lang} {cversion} {wversion}'.format(lang=language, cversion=creatorV, wversion=waldayuV))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
`

**Comment by roedoejet** [comment]
Hm, maybe try passing shell=true as an argument to subprocess.call if that doesn't work you could try finding the absolute path to ask the arguments and then passing those instead of relative paths. I guess this a Mac terminal path issue... Good luck. If nothing works I can try and find a Mac and if I can't figure it out

**Comment by Kedersha** [comment]
Yesss that worked! I'd tried doing the absolute path before, to no avail, but adding `shell='TRUE'` seems to have done the trick. :) Thanks!

**Comment by roedoejet** [comment]
silly macs...everything else is running properly then?

**Comment by Kedersha** [comment]
yes it seems to be!
I managed to serve the Heiltsuk app to Ionic without any errors, and played around with it in Chrome a little. I'm still an Ionic newbie though, so I am having doubts about whether "serve" was the right thing to do.

**Comment by roedoejet** [comment]
very cool! yes, serve is the right thing to do! running main.py should actually run ionic serve automatically after building the app...perhaps another shell=true issue...oh well!
